### ISSUE TITLE
TOTP wrong code

### ISSUE THREAD

**Issue by kapitolinakuznetsova** [mdp/rotp#101]
It seems like `verify` works wrong sometimes. I'm trying to verify code at the moment it was created: 

```
totp = ROTP::TOTP.new(ROTP::Base32.random)

loop.with_index do |_, i|
  interval = totp.verify(totp.now)

  unless interval
    puts "break at #{i}"
    break
  end
end

# receive
break at 184357
```

While same code with `interval: 1` and `drift_behind: 30` works perfect even with verify `at: (Time.now+29)`:

```
totp = ROTP::TOTP.new(ROTP::Base32.random, interval: 1)

loop.with_index do |_, i|
  interval = totp.verify(totp.now,
                         at: Time.now + 29,
                         drift_behind: 30 )

  unless interval
    puts "break at #{i}"
    break
  end
end
#no breaks for 1,5+ millions attempts
```

Maybe it is related to integer division at [timecode method](https://github.com/mdp/rotp/blob/master/lib/rotp/totp.rb#L77)?

**Comment by mdp** [comment]
Interesting, I'm swamped at the moment, but I'll try and tackle it this weekend. Thanks for the test cases/example code.

**Comment by mdp** [comment]
So this actually makes sense because there's a case where you can generate an OTP in one period and verify it in another in the time that it takes Ruby to create the timestamp and then verify it.

For example - You generate the code at 15:23:29.999999999, but when you go to verify it, it's now 15:23:30.0000001, because these are two separate steps.

If you want to solve for this, I think you'd need to either allow for a drift behind of a second or two, or lock in the timestamp and make sure it's used for both creation and verification:

```ruby
totp = ROTP::TOTP.new(ROTP::Base32.random, interval: 1)

loop.with_index do |_, i|
  timestamp = Time.now
  interval = totp.verify(totp.at(timestamp),
                         at: timestamp )

  unless interval
    puts "break at #{i}"
    break
  end
end
```

Feel free to reopen if this doesn't solve your issue.
